// Source: ORNL/GridKit PhasorDynamics data enums and parameter readers at GRIDKIT_REVISION.
export const GRIDKIT_REVISION = '5c8b789df9d7eee161f468f042b8decb064bd0f7'
export interface ModelContract {
  readonly parameters: readonly string[]
  readonly buses: readonly string[]
  readonly inputs: readonly string[]
  readonly outputs: readonly string[]
  readonly monitors: readonly string[]
  /** Legacy readers require JSON real tokens, even for integral values. */
  readonly realParameters: readonly string[]
}
export const CONTRACT: Readonly<Record<string, ModelContract>> = {
  Branch: {
    parameters: ['R', 'X', 'G', 'B', 'Gmag', 'Bmag', 'tap', 'phase'],
    buses: ['bus1', 'bus2'],
    inputs: [],
    outputs: [],
    monitors: ['ir1', 'ii1', 'im1', 'p1', 'q1', 'ir2', 'ii2', 'im2', 'p2', 'q2'],
    realParameters: [],
  },
  Bus: {
    parameters: ['kv'],
    buses: [],
    inputs: [],
    outputs: [],
    monitors: ['Vr', 'Vi', 'Vm', 'Va'],
    realParameters: [],
  },
  BusFault: {
    parameters: ['state0', 'R', 'X'],
    buses: ['bus'],
    inputs: ['control_signal'],
    outputs: [],
    monitors: ['state', 'ir', 'ii'],
    realParameters: ['R', 'X'],
  },
  BusToSignalAdapter: {
    parameters: [],
    buses: ['bus'],
    inputs: ['ir', 'ii'],
    outputs: ['vr', 'vi'],
    monitors: [],
    realParameters: [],
  },
  ConstantSignalSource: {
    parameters: ['Sr', 'Si'],
    buses: [],
    inputs: [],
    outputs: ['sr', 'si'],
    monitors: [],
    realParameters: ['Sr', 'Si'],
  },
  Esdc1a: {
    parameters: [
      'Tr',
      'Ka',
      'Ta',
      'Tb',
      'Tc',
      'Vrmax',
      'Vrmin',
      'Ke',
      'Te',
      'Kf',
      'Tf1',
      'Spdmlt',
      'E1',
      'Se1',
      'E2',
      'Se2',
      'UEL',
      'exclim',
    ],
    buses: ['bus'],
    inputs: ['speed', 'vref', 'vs', 'vuel'],
    outputs: ['efd'],
    monitors: ['efd', 'vc', 'vr', 'vf', 'se', 'vfe'],
    realParameters: [],
  },
  GastPti: {
    parameters: ['R', 'T1', 'T2', 'T3', 'At', 'Kt', 'Vmax', 'Vmin', 'Dturb', 'Trate'],
    buses: [],
    inputs: ['speed', 'pref'],
    outputs: ['pmech'],
    monitors: ['pmech', 'xvalve', 'xflow', 'xtemp', 'vload', 'vtemp'],
    realParameters: [],
  },
  GenClassical: {
    parameters: ['p0', 'q0', 'H', 'D', 'Ra', 'Xdp', 'mva'],
    buses: ['bus'],
    inputs: ['pmech', 'efd'],
    outputs: ['speed'],
    monitors: ['ir', 'ii', 'p', 'q', 'delta', 'omega', 'speed'],
    realParameters: ['p0', 'q0', 'H', 'D', 'Ra', 'Xdp', 'mva'],
  },
  Genrou: {
    parameters: [
      'p0',
      'q0',
      'H',
      'D',
      'Ra',
      'Tdop',
      'Tdopp',
      'Tqop',
      'Tqopp',
      'Xd',
      'Xdp',
      'Xdpp',
      'Xq',
      'Xqp',
      'Xqpp',
      'Xl',
      'S10',
      'S12',
      'mva',
    ],
    buses: ['bus'],
    inputs: ['pmech', 'efd'],
    outputs: ['speed'],
    monitors: ['ir', 'ii', 'p', 'q', 'delta', 'omega', 'speed'],
    realParameters: [
      'p0',
      'q0',
      'H',
      'D',
      'Ra',
      'Tdop',
      'Tdopp',
      'Tqopp',
      'Tqop',
      'Xd',
      'Xdp',
      'Xdpp',
      'Xq',
      'Xqp',
      'Xqpp',
      'Xl',
      'S10',
      'S12',
      'mva',
    ],
  },
  Gensal: {
    parameters: [
      'p0',
      'q0',
      'H',
      'D',
      'Ra',
      'Tdop',
      'Tdopp',
      'Tqopp',
      'Xd',
      'Xdp',
      'Xdpp',
      'Xq',
      'Xl',
      'S10',
      'S12',
      'mva',
    ],
    buses: ['bus'],
    inputs: ['pmech', 'efd'],
    outputs: ['speed'],
    monitors: [
      'ir',
      'ii',
      'p',
      'q',
      'delta',
      'omega',
      'speed',
      'Eqp',
      'psidp',
      'psiqpp',
      'psidpp',
      'vd',
      'vq',
      'te',
      'id',
      'iq',
    ],
    realParameters: [
      'p0',
      'q0',
      'H',
      'D',
      'Ra',
      'Tdop',
      'Tdopp',
      'Tqopp',
      'Xd',
      'Xdp',
      'Xdpp',
      'Xq',
      'Xl',
      'S10',
      'S12',
      'mva',
    ],
  },
  Hygov: {
    parameters: [
      'Trate',
      'Rperm',
      'Rtemp',
      'Tr',
      'Tf',
      'Tg',
      'Velm',
      'Gmax',
      'Gmin',
      'Tw',
      'At',
      'Dturb',
      'Qnl',
      'Tn',
      'Tnp',
      'db1',
      'db2',
      'Hdam',
      'Gv0',
      'Gv1',
      'Gv2',
      'Gv3',
      'Gv4',
      'Gv5',
      'Pgv0',
      'Pgv1',
      'Pgv2',
      'Pgv3',
      'Pgv4',
      'Pgv5',
    ],
    buses: [],
    inputs: ['speed', 'pref', 'paux'],
    outputs: ['pmech'],
    monitors: ['pmech', 'filter', 'desiredgate', 'gate', 'flow', 'head'],
    realParameters: [],
  },
  Ieeest: {
    parameters: [
      'A1',
      'A2',
      'A3',
      'A4',
      'A5',
      'A6',
      'T1',
      'T2',
      'T3',
      'T4',
      'T5',
      'T6',
      'Ks',
      'Lsmin',
      'Lsmax',
      'Vcl',
      'Vcu',
      'Tdelay',
    ],
    buses: [],
    inputs: ['input'],
    outputs: ['output'],
    monitors: ['vss'],
    realParameters: [
      'A1',
      'A2',
      'A3',
      'A4',
      'A5',
      'A6',
      'T1',
      'T2',
      'T3',
      'T4',
      'T5',
      'T6',
      'Ks',
      'Lsmin',
      'Lsmax',
      'Vcl',
      'Vcu',
      'Tdelay',
    ],
  },
  Ieeet1: {
    parameters: [
      'Tr',
      'Ka',
      'Ta',
      'Ke',
      'Te',
      'Kf',
      'Tf',
      'Vrmin',
      'Vrmax',
      'E1',
      'E2',
      'Se1',
      'Se2',
      'Ispdlim',
    ],
    buses: ['bus'],
    inputs: ['speed', 'vref', 'vs', 'vuel', 'voel'],
    outputs: ['efd'],
    monitors: ['efd', 'ksat'],
    realParameters: [
      'Tr',
      'Ka',
      'Ta',
      'Ke',
      'Te',
      'Kf',
      'Tf',
      'Vrmin',
      'Vrmax',
      'E1',
      'E2',
      'Se1',
      'Se2',
      'Ispdlim',
    ],
  },
  LoadZ: {
    parameters: ['R', 'X'],
    buses: ['bus'],
    inputs: [],
    outputs: [],
    monitors: ['p', 'q'],
    realParameters: ['R', 'X'],
  },
  LoadZIP: {
    parameters: ['Pnom', 'Qnom', 'alphaI', 'alphaP'],
    buses: ['bus'],
    inputs: [],
    outputs: [],
    monitors: ['ir', 'ii', 'im', 'p', 'q'],
    realParameters: ['Pnom', 'Qnom', 'alphaI', 'alphaP'],
  },
  Reecb: {
    parameters: [
      'mva',
      'PfFlag',
      'VFlag',
      'QFlag',
      'Pqflag',
      'Trv',
      'Tp',
      'Vref0',
      'Vdip',
      'Vup',
      'dbd1',
      'dbd2',
      'kqv',
      'Iql1',
      'Iqh1',
      'Qmax',
      'Qmin',
      'Kqp',
      'Kqi',
      'Vmax',
      'Vmin',
      'Kvp',
      'Kvi',
      'Tiq',
      'Tpord',
      'dPmax',
      'dPmin',
      'Pmax',
      'Pmin',
      'Imax',
    ],
    buses: ['bus'],
    inputs: ['pe', 'qgen', 'qext', 'pfaref', 'pref'],
    outputs: ['iqcmd', 'ipcmd'],
    monitors: ['iqcmd', 'ipcmd', 'vmeas', 'pmeas'],
    realParameters: [],
  },
  Regca: {
    parameters: [
      'p0',
      'q0',
      'mva',
      'Tg',
      'TM',
      'Rqmax',
      'Rqmin',
      'Rpmax',
      'sL',
      'IL1',
      'VL0',
      'VL1',
      'VA0',
      'VA1',
      'Vhvmax',
      'Qmin',
      'Khv',
      'Xe',
    ],
    buses: ['bus'],
    inputs: ['ipcmd', 'iqcmd'],
    outputs: ['ibranchr', 'ibranchi', 'pbranch', 'qbranch'],
    monitors: ['ir', 'ii', 'p', 'q'],
    realParameters: [],
  },
  Repca: {
    parameters: [
      'mva',
      'VcompFlag',
      'RefFlag',
      'Freqflag',
      'Tfltr',
      'Vfrz',
      'Rc',
      'Xc',
      'Kc',
      'dbdlow',
      'dbdupper',
      'emax',
      'emin',
      'Kp',
      'Ki',
      'Qmax',
      'Qmin',
      'Tft',
      'Tfv',
      'Tp',
      'fdbd1',
      'fdbd2',
      'Ddn',
      'Dup',
      'femax',
      'femin',
      'Kpg',
      'Kig',
      'Pmax',
      'Pmin',
      'Tlag',
    ],
    buses: ['bus'],
    inputs: ['ir', 'ii', 'p', 'q', 'freq', 'vref', 'pref', 'qref', 'freqref'],
    outputs: ['qext', 'pext'],
    monitors: ['qext', 'pext', 'vmeas', 'qmeas', 'pmeas'],
    realParameters: [],
  },
  SexsPti: {
    parameters: ['Ta', 'Tb', 'Te', 'K', 'Efdmax', 'Efdmin'],
    buses: ['bus'],
    inputs: ['vref', 'vs', 'vuel', 'voel'],
    outputs: ['efd'],
    monitors: ['efd'],
    realParameters: ['Ta', 'Tb', 'Te', 'K', 'Efdmax', 'Efdmin'],
  },
  Tgov1: {
    parameters: ['Trate', 'R', 'T1', 'T2', 'T3', 'Pvmax', 'Pvmin', 'Dt'],
    buses: [],
    inputs: ['speed', 'pref'],
    outputs: ['pmech'],
    monitors: [],
    realParameters: ['Trate', 'R', 'Pvmin', 'Pvmax', 'T1', 'T2', 'T3', 'Dt'],
  },
}

export function modelContract(name: string): ModelContract | undefined {
  const key = name === 'BusInfinite' ? 'Bus' : name
  return Object.hasOwn(CONTRACT, key) ? CONTRACT[key] : undefined
}
