/** Dependency-free stdio relay. GridKit owns the MCP server and all tool execution. */
import { readdir, readFile, stat } from 'node:fs/promises'
import { connect, type Socket } from 'node:net'
import { join } from 'node:path'

type Connection = { format: number; address: string; token: string; instance: string }

async function readConnection(path: string): Promise<Connection> {
  if ((await stat(path)).size > 4096) throw new Error('Invalid GridKit connection record.')
  const value = JSON.parse(await readFile(path, 'utf8')) as Connection
  if (
    value.format !== 1 ||
    typeof value.address !== 'string' ||
    !/^[a-f0-9]{64}$/.test(value.token) ||
    !/^[a-f0-9-]{36}$/.test(value.instance)
  )
    throw new Error('Unsupported GridKit connection record. Reconnect from VS Code.')
  if (process.platform === 'win32' && !value.address.startsWith('\\\\.\\pipe\\gridkit-'))
    throw new Error('GridKit requires a local named pipe.')
  return value
}

/** Authentication precedes MCP framing; credentials never appear in stdout or config. */
function open(connection: Connection, probe = false): Promise<Socket> {
  return new Promise((resolve, reject) => {
    const socket = connect(connection.address)
    let response = ''
    const timer = setTimeout(() => fail(new Error('GridKit connection timed out.')), 5000)
    const fail = (error: Error) => {
      cleanup()
      socket.destroy()
      reject(error)
    }
    const closed = () => fail(new Error('GridKit closed the connection.'))
    const cleanup = () => {
      clearTimeout(timer)
      socket.off('data', data)
      socket.off('error', fail)
      socket.off('close', closed)
    }
    const data = (chunk: Buffer) => {
      response += chunk.toString('utf8')
      if (response.length > 3 || (response.includes('\n') && response !== 'OK\n'))
        return fail(new Error('GridKit authentication failed. Reconnect from VS Code.'))
      if (response === 'OK\n') {
        socket.pause()
        cleanup()
        resolve(socket)
      }
    }
    socket.on('error', fail).on('close', closed).on('data', data)
    socket.once('connect', () =>
      socket.write(`${probe ? 'probe' : 'connect'} ${connection.token}\n`),
    )
  })
}

async function main() {
  const [option, path, ...extra] = process.argv.slice(2)
  if (!path || extra.length || !['--directory', '--connection'].includes(option ?? ''))
    throw new Error(
      'Use the connection command generated by GridKit Studio: Connect AI Client in VS Code.',
    )
  let connection: Connection
  if (option === '--connection') connection = await readConnection(path)
  else {
    const files = (await readdir(path)).filter((name) => /^[a-f0-9-]{36}\.json$/.test(name))
    const candidates = await Promise.all(
      files.map(async (name) => {
        try {
          const value = await readConnection(join(path, name))
          const socket = await open(value, true)
          socket.destroy()
          return value
        } catch {
          return undefined
        }
      }),
    )
    const live = candidates.filter((value): value is Connection => !!value)
    if (!live.length)
      throw new Error(
        'GridKit is not connected. Open this workspace in VS Code and run GridKit Studio: Connect AI Client.',
      )
    if (live.length !== 1)
      throw new Error(
        'Multiple GridKit windows are connected for this workspace. Disconnect the others or use the exact-window configuration from Connect AI Client.',
      )
    connection = live[0]!
  }
  const socket = await open(connection)
  const close = () => {
    process.stdin.unpipe(socket)
    process.stdin.pause()
    socket.destroy()
  }
  socket.on('error', (error) => {
    console.error(error.message)
    process.exitCode = 1
    close()
  })
  socket.on('close', close)
  process.stdin.on('error', close).on('end', close)
  process.stdout.on('error', close)
  process.on('SIGTERM', close).on('SIGINT', close)
  socket.pipe(process.stdout)
  process.stdin.pipe(socket)
  socket.resume()
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exitCode = 1
})
